### ISSUE TITLE
Current Fitness Prop Select breaks if fitness is negative

### ISSUE THREAD

**Issue by ambarket** [Akiira/Comp-524-program#9]
Just playing around with the fitness function, found this. Not sure what our plans are for fitness and if we'll need or want negative values.

**Comment by Akiira** [comment]
Well it depends on how we punish repeated coverage. I was thinking everytime an edge is covered mutliple times we only give it a fraction of the base reward for each time it is covered more then once. We could even keep lowering that fraction as it covered it more times. In this case it would never get negative fitness.
